// Generated by `wit-bindgen` 0.51.0. DO NOT EDIT!
// Options used:
#[allow(dead_code, clippy::all)]
pub mod astrobox {
  pub mod psys {

    #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
    pub mod psys_host {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::__link_custom_section_describing_imports;
      
      use super::super::super::_rt;
      #[repr(u8)]
      #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
      pub enum ElementType {
        Div,
        P,
        Button,
        Input,
        Select,
        Opt,
      }
      impl ::core::fmt::Debug for ElementType {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          match self {
            ElementType::Div => {
              f.debug_tuple("ElementType::Div").finish()
            }
            ElementType::P => {
              f.debug_tuple("ElementType::P").finish()
            }
            ElementType::Button => {
              f.debug_tuple("ElementType::Button").finish()
            }
            ElementType::Input => {
              f.debug_tuple("ElementType::Input").finish()
            }
            ElementType::Select => {
              f.debug_tuple("ElementType::Select").finish()
            }
            ElementType::Opt => {
              f.debug_tuple("ElementType::Opt").finish()
            }
          }
        }
      }

      impl ElementType{
        #[doc(hidden)]
        pub unsafe fn _lift(val: u8) -> ElementType{
          if !cfg!(debug_assertions) {
            return unsafe { ::core::mem::transmute(val) };
          }

          match val {
            0 => ElementType::Div,
            1 => ElementType::P,
            2 => ElementType::Button,
            3 => ElementType::Input,
            4 => ElementType::Select,
            5 => ElementType::Opt,

            _ => panic!("invalid enum discriminant"),
          }
        }
      }

      #[repr(u8)]
      #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
      pub enum UiEvent {
        Click,
        Change,
        MouseEnter,
        MouseLeave,
        Focus,
        Blur,
        Submit,
        Input,
      }
      impl ::core::fmt::Debug for UiEvent {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          match self {
            UiEvent::Click => {
              f.debug_tuple("UiEvent::Click").finish()
            }
            UiEvent::Change => {
              f.debug_tuple("UiEvent::Change").finish()
            }
            UiEvent::MouseEnter => {
              f.debug_tuple("UiEvent::MouseEnter").finish()
            }
            UiEvent::MouseLeave => {
              f.debug_tuple("UiEvent::MouseLeave").finish()
            }
            UiEvent::Focus => {
              f.debug_tuple("UiEvent::Focus").finish()
            }
            UiEvent::Blur => {
              f.debug_tuple("UiEvent::Blur").finish()
            }
            UiEvent::Submit => {
              f.debug_tuple("UiEvent::Submit").finish()
            }
            UiEvent::Input => {
              f.debug_tuple("UiEvent::Input").finish()
            }
          }
        }
      }

      impl UiEvent{
        #[doc(hidden)]
        pub unsafe fn _lift(val: u8) -> UiEvent{
          if !cfg!(debug_assertions) {
            return unsafe { ::core::mem::transmute(val) };
          }

          match val {
            0 => UiEvent::Click,
            1 => UiEvent::Change,
            2 => UiEvent::MouseEnter,
            3 => UiEvent::MouseLeave,
            4 => UiEvent::Focus,
            5 => UiEvent::Blur,
            6 => UiEvent::Submit,
            7 => UiEvent::Input,

            _ => panic!("invalid enum discriminant"),
          }
        }
      }

      #[repr(u8)]
      #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
      pub enum FlexDirection {
        Row,
        Column,
      }
      impl ::core::fmt::Debug for FlexDirection {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          match self {
            FlexDirection::Row => {
              f.debug_tuple("FlexDirection::Row").finish()
            }
            FlexDirection::Column => {
              f.debug_tuple("FlexDirection::Column").finish()
            }
          }
        }
      }

      impl FlexDirection{
        #[doc(hidden)]
        pub unsafe fn _lift(val: u8) -> FlexDirection{
          if !cfg!(debug_assertions) {
            return unsafe { ::core::mem::transmute(val) };
          }

          match val {
            0 => FlexDirection::Row,
            1 => FlexDirection::Column,

            _ => panic!("invalid enum discriminant"),
          }
        }
      }

      #[derive(Clone)]
      pub struct Element {
        pub element_type: ElementType,
        pub text: Option<_rt::String>,
        pub children: _rt::Vec::<_rt::String>,
        pub on_events: _rt::Vec::<(UiEvent,_rt::String,)>,
        pub styles: _rt::Vec::<(_rt::String,_rt::String,)>,
      }
      impl ::core::fmt::Debug for Element {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          f.debug_struct("Element").field("element-type", &self.element_type).field("text", &self.text).field("children", &self.children).field("on-events", &self.on_events).field("styles", &self.styles).finish()
        }
      }
      #[derive(Clone)]
      pub struct DeviceInfo {
        pub addr: _rt::String,
        pub name: _rt::String,
      }
      impl ::core::fmt::Debug for DeviceInfo {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          f.debug_struct("DeviceInfo").field("addr", &self.addr).field("name", &self.name).finish()
        }
      }
      #[derive(Clone)]
      pub struct AppInfo {
        pub package_name: _rt::String,
        pub version_code: u32,
        pub version_name: _rt::String,
      }
      impl ::core::fmt::Debug for AppInfo {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          f.debug_struct("AppInfo").field("package-name", &self.package_name).field("version-code", &self.version_code).field("version-name", &self.version_name).finish()
        }
      }
      #[allow(unused_unsafe, clippy::all)]
      #[allow(async_fn_in_trait)]
      pub fn render(a: &str,b: &Element,) -> (){
        unsafe {
          let vec0 = a;
          let ptr0 = vec0.as_ptr().cast::<u8>();
          let len0 = vec0.len();
          let Element{ element_type:element_type1, text:text1, children:children1, on_events:on_events1, styles:styles1, } = b;
          let (result3_0,result3_1,result3_2,) = match text1 {
            Some(e) => {
              let vec2 = e;
              let ptr2 = vec2.as_ptr().cast::<u8>();
              let len2 = vec2.len();

              (1i32, ptr2.cast_mut(), len2)
            },
            None => {
              (0i32, ::core::ptr::null_mut(), 0usize)
            },
          };let vec5 = children1;
          let len5 = vec5.len();
          let layout5 = _rt::alloc::Layout::from_size_align(vec5.len() * (2*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>()).unwrap();
          let (result5, _cleanup5) = wit_bindgen::rt::Cleanup::new(layout5);for (i, e) in vec5.into_iter().enumerate() {
            let base = result5.add(i * (2*::core::mem::size_of::<*const u8>()));
            {
              let vec4 = e;
              let ptr4 = vec4.as_ptr().cast::<u8>();
              let len4 = vec4.len();
              *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
              *base.add(0).cast::<*mut u8>() = ptr4.cast_mut();
            }
          }
          let vec8 = on_events1;
          let len8 = vec8.len();
          let layout8 = _rt::alloc::Layout::from_size_align(vec8.len() * (3*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>()).unwrap();
          let (result8, _cleanup8) = wit_bindgen::rt::Cleanup::new(layout8);for (i, e) in vec8.into_iter().enumerate() {
            let base = result8.add(i * (3*::core::mem::size_of::<*const u8>()));
            {
              let (t6_0, t6_1, ) = e;
              *base.add(0).cast::<u8>() = (t6_0.clone() as i32) as u8;
              let vec7 = t6_1;
              let ptr7 = vec7.as_ptr().cast::<u8>();
              let len7 = vec7.len();
              *base.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>() = len7;
              *base.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr7.cast_mut();
            }
          }
          let vec12 = styles1;
          let len12 = vec12.len();
          let layout12 = _rt::alloc::Layout::from_size_align(vec12.len() * (4*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>()).unwrap();
          let (result12, _cleanup12) = wit_bindgen::rt::Cleanup::new(layout12);for (i, e) in vec12.into_iter().enumerate() {
            let base = result12.add(i * (4*::core::mem::size_of::<*const u8>()));
            {
              let (t9_0, t9_1, ) = e;
              let vec10 = t9_0;
              let ptr10 = vec10.as_ptr().cast::<u8>();
              let len10 = vec10.len();
              *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len10;
              *base.add(0).cast::<*mut u8>() = ptr10.cast_mut();
              let vec11 = t9_1;
              let ptr11 = vec11.as_ptr().cast::<u8>();
              let len11 = vec11.len();
              *base.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>() = len11;
              *base.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr11.cast_mut();
            }
          }

          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "astrobox:psys/psys-host@0.1.0")]
          unsafe extern "C" {
            #[link_name = "render"]
            fn wit_import13(_: *mut u8, _: usize, _: i32, _: i32, _: *mut u8, _: usize, _: *mut u8, _: usize, _: *mut u8, _: usize, _: *mut u8, _: usize, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import13(_: *mut u8, _: usize, _: i32, _: i32, _: *mut u8, _: usize, _: *mut u8, _: usize, _: *mut u8, _: usize, _: *mut u8, _: usize, ) { unreachable!() }
          wit_import13(ptr0.cast_mut(), len0, element_type1.clone() as i32, result3_0, result3_1, result3_2, result5, len5, result8, len8, result12, len12);
        }
      }
      #[allow(unused_unsafe, clippy::all)]
      #[allow(async_fn_in_trait)]
      pub fn get_connected_device_list() -> _rt::Vec::<DeviceInfo>{
        unsafe {

          #[cfg_attr(target_pointer_width="64", repr(align(8)))]
          #[cfg_attr(target_pointer_width="32", repr(align(4)))]
          struct RetArea([::core::mem::MaybeUninit::<u8>; 2*::core::mem::size_of::<*const u8>()]);
          let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 2*::core::mem::size_of::<*const u8>()]);
          let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "astrobox:psys/psys-host@0.1.0")]
          unsafe extern "C" {
            #[link_name = "get-connected-device-list"]
            fn wit_import1(_: *mut u8, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import1(_: *mut u8, ) { unreachable!() }
          wit_import1(ptr0);
          let l2 = *ptr0.add(0).cast::<*mut u8>();
          let l3 = *ptr0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
          let base10 = l2;
          let len10 = l3;
          let mut result10 = _rt::Vec::with_capacity(len10);
          for i in 0..len10 {
            let base = base10.add(i * (4*::core::mem::size_of::<*const u8>()));
            let e10 = {
              let l4 = *base.add(0).cast::<*mut u8>();
              let l5 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
              let len6 = l5;
              let bytes6 = _rt::Vec::from_raw_parts(l4.cast(), len6, len6);
              let l7 = *base.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
              let l8 = *base.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
              let len9 = l8;
              let bytes9 = _rt::Vec::from_raw_parts(l7.cast(), len9, len9);

              DeviceInfo{
                addr: _rt::string_lift(bytes6),
                name: _rt::string_lift(bytes9),
              }
            };
            result10.push(e10);
          }
          _rt::cabi_dealloc(base10, len10 * (4*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());
          let result11 = result10;
          result11
        }
      }
      #[allow(unused_unsafe, clippy::all)]
      #[allow(async_fn_in_trait)]
      pub fn send_qaic_message(a: &str,b: &str,c: &str,) -> Result<(),_rt::String>{
        unsafe {

          #[cfg_attr(target_pointer_width="64", repr(align(8)))]
          #[cfg_attr(target_pointer_width="32", repr(align(4)))]
          struct RetArea([::core::mem::MaybeUninit::<u8>; 3*::core::mem::size_of::<*const u8>()]);
          let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 3*::core::mem::size_of::<*const u8>()]);
          let vec0 = a;
          let ptr0 = vec0.as_ptr().cast::<u8>();
          let len0 = vec0.len();
          let vec1 = b;
          let ptr1 = vec1.as_ptr().cast::<u8>();
          let len1 = vec1.len();
          let vec2 = c;
          let ptr2 = vec2.as_ptr().cast::<u8>();
          let len2 = vec2.len();
          let ptr3 = ret_area.0.as_mut_ptr().cast::<u8>();
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "astrobox:psys/psys-host@0.1.0")]
          unsafe extern "C" {
            #[link_name = "send-qaic-message"]
            fn wit_import4(_: *mut u8, _: usize, _: *mut u8, _: usize, _: *mut u8, _: usize, _: *mut u8, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import4(_: *mut u8, _: usize, _: *mut u8, _: usize, _: *mut u8, _: usize, _: *mut u8, ) { unreachable!() }
          wit_import4(ptr0.cast_mut(), len0, ptr1.cast_mut(), len1, ptr2.cast_mut(), len2, ptr3);
          let l5 = i32::from(*ptr3.add(0).cast::<u8>());
          let result9 = match l5 {
            0 => {
              let e = ();
              Ok(e)
            }
            1 => {
              let e = {
                let l6 = *ptr3.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                let l7 = *ptr3.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
                let len8 = l7;
                let bytes8 = _rt::Vec::from_raw_parts(l6.cast(), len8, len8);

                _rt::string_lift(bytes8)
              };
              Err(e)
            }
            _ => _rt::invalid_enum_discriminant(),
          };
          result9
        }
      }
      #[allow(unused_unsafe, clippy::all)]
      #[allow(async_fn_in_trait)]
      pub fn register_interconnect_recv(a: &str,b: &str,) -> Result<(),_rt::String>{
        unsafe {

          #[cfg_attr(target_pointer_width="64", repr(align(8)))]
          #[cfg_attr(target_pointer_width="32", repr(align(4)))]
          struct RetArea([::core::mem::MaybeUninit::<u8>; 3*::core::mem::size_of::<*const u8>()]);
          let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 3*::core::mem::size_of::<*const u8>()]);
          let vec0 = a;
          let ptr0 = vec0.as_ptr().cast::<u8>();
          let len0 = vec0.len();
          let vec1 = b;
          let ptr1 = vec1.as_ptr().cast::<u8>();
          let len1 = vec1.len();
          let ptr2 = ret_area.0.as_mut_ptr().cast::<u8>();
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "astrobox:psys/psys-host@0.1.0")]
          unsafe extern "C" {
            #[link_name = "register-interconnect-recv"]
            fn wit_import3(_: *mut u8, _: usize, _: *mut u8, _: usize, _: *mut u8, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import3(_: *mut u8, _: usize, _: *mut u8, _: usize, _: *mut u8, ) { unreachable!() }
          wit_import3(ptr0.cast_mut(), len0, ptr1.cast_mut(), len1, ptr2);
          let l4 = i32::from(*ptr2.add(0).cast::<u8>());
          let result8 = match l4 {
            0 => {
              let e = ();
              Ok(e)
            }
            1 => {
              let e = {
                let l5 = *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                let l6 = *ptr2.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
                let len7 = l6;
                let bytes7 = _rt::Vec::from_raw_parts(l5.cast(), len7, len7);

                _rt::string_lift(bytes7)
              };
              Err(e)
            }
            _ => _rt::invalid_enum_discriminant(),
          };
          result8
        }
      }
      #[allow(unused_unsafe, clippy::all)]
      #[allow(async_fn_in_trait)]
      pub fn get_thirdparty_app_list(a: &str,) -> Result<_rt::Vec::<AppInfo>,_rt::String>{
        unsafe {

          #[cfg_attr(target_pointer_width="64", repr(align(8)))]
          #[cfg_attr(target_pointer_width="32", repr(align(4)))]
          struct RetArea([::core::mem::MaybeUninit::<u8>; 3*::core::mem::size_of::<*const u8>()]);
          let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 3*::core::mem::size_of::<*const u8>()]);
          let vec0 = a;
          let ptr0 = vec0.as_ptr().cast::<u8>();
          let len0 = vec0.len();
          let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "astrobox:psys/psys-host@0.1.0")]
          unsafe extern "C" {
            #[link_name = "get-thirdparty-app-list"]
            fn wit_import2(_: *mut u8, _: usize, _: *mut u8, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import2(_: *mut u8, _: usize, _: *mut u8, ) { unreachable!() }
          wit_import2(ptr0.cast_mut(), len0, ptr1);
          let l3 = i32::from(*ptr1.add(0).cast::<u8>());
          let result17 = match l3 {
            0 => {
              let e = {
                let l4 = *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                let l5 = *ptr1.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
                let base13 = l4;
                let len13 = l5;
                let mut result13 = _rt::Vec::with_capacity(len13);
                for i in 0..len13 {
                  let base = base13.add(i * (5*::core::mem::size_of::<*const u8>()));
                  let e13 = {
                    let l6 = *base.add(0).cast::<*mut u8>();
                    let l7 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
                    let len8 = l7;
                    let bytes8 = _rt::Vec::from_raw_parts(l6.cast(), len8, len8);
                    let l9 = *base.add(2*::core::mem::size_of::<*const u8>()).cast::<i32>();
                    let l10 = *base.add(3*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                    let l11 = *base.add(4*::core::mem::size_of::<*const u8>()).cast::<usize>();
                    let len12 = l11;
                    let bytes12 = _rt::Vec::from_raw_parts(l10.cast(), len12, len12);

                    AppInfo{
                      package_name: _rt::string_lift(bytes8),
                      version_code: l9 as u32,
                      version_name: _rt::string_lift(bytes12),
                    }
                  };
                  result13.push(e13);
                }
                _rt::cabi_dealloc(base13, len13 * (5*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());

                result13
              };
              Ok(e)
            }
            1 => {
              let e = {
                let l14 = *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                let l15 = *ptr1.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
                let len16 = l15;
                let bytes16 = _rt::Vec::from_raw_parts(l14.cast(), len16, len16);

                _rt::string_lift(bytes16)
              };
              Err(e)
            }
            _ => _rt::invalid_enum_discriminant(),
          };
          result17
        }
      }
      #[allow(unused_unsafe, clippy::all)]
      #[allow(async_fn_in_trait)]
      pub fn launch_qa(a: &str,b: &AppInfo,c: &str,) -> Result<(),_rt::String>{
        unsafe {

          #[cfg_attr(target_pointer_width="64", repr(align(8)))]
          #[cfg_attr(target_pointer_width="32", repr(align(4)))]
          struct RetArea([::core::mem::MaybeUninit::<u8>; 3*::core::mem::size_of::<*const u8>()]);
          let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 3*::core::mem::size_of::<*const u8>()]);
          let vec0 = a;
          let ptr0 = vec0.as_ptr().cast::<u8>();
          let len0 = vec0.len();
          let AppInfo{ package_name:package_name1, version_code:version_code1, version_name:version_name1, } = b;
          let vec2 = package_name1;
          let ptr2 = vec2.as_ptr().cast::<u8>();
          let len2 = vec2.len();
          let vec3 = version_name1;
          let ptr3 = vec3.as_ptr().cast::<u8>();
          let len3 = vec3.len();
          let vec4 = c;
          let ptr4 = vec4.as_ptr().cast::<u8>();
          let len4 = vec4.len();
          let ptr5 = ret_area.0.as_mut_ptr().cast::<u8>();
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "astrobox:psys/psys-host@0.1.0")]
          unsafe extern "C" {
            #[link_name = "launch-qa"]
            fn wit_import6(_: *mut u8, _: usize, _: *mut u8, _: usize, _: i32, _: *mut u8, _: usize, _: *mut u8, _: usize, _: *mut u8, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import6(_: *mut u8, _: usize, _: *mut u8, _: usize, _: i32, _: *mut u8, _: usize, _: *mut u8, _: usize, _: *mut u8, ) { unreachable!() }
          wit_import6(ptr0.cast_mut(), len0, ptr2.cast_mut(), len2, _rt::as_i32(version_code1), ptr3.cast_mut(), len3, ptr4.cast_mut(), len4, ptr5);
          let l7 = i32::from(*ptr5.add(0).cast::<u8>());
          let result11 = match l7 {
            0 => {
              let e = ();
              Ok(e)
            }
            1 => {
              let e = {
                let l8 = *ptr5.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                let l9 = *ptr5.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
                let len10 = l9;
                let bytes10 = _rt::Vec::from_raw_parts(l8.cast(), len10, len10);

                _rt::string_lift(bytes10)
              };
              Err(e)
            }
            _ => _rt::invalid_enum_discriminant(),
          };
          result11
        }
      }
      #[allow(unused_unsafe, clippy::all)]
      #[allow(async_fn_in_trait)]
      pub fn timezone_offset_minutes() -> i32{
        unsafe {

          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "astrobox:psys/psys-host@0.1.0")]
          unsafe extern "C" {
            #[link_name = "timezone-offset-minutes"]
            fn wit_import0() -> i32;
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import0() -> i32 { unreachable!() }
          let ret = wit_import0();
          ret
        }
      }

    }

  }
}
#[allow(dead_code, clippy::all)]
pub mod exports {
  pub mod astrobox {
    pub mod psys {

      #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
      pub mod psys_plugin {
        #[used]
        #[doc(hidden)]
        static __FORCE_SECTION_REF: fn() =
        super::super::super::super::__link_custom_section_describing_imports;
        
        use super::super::super::super::_rt;
        #[repr(u8)]
        #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
        pub enum EventType {
          PluginMessage,
          InterconnectMessage,
          DeviceAction,
          ProviderAction,
          DeeplinkAction,
          TransportPacket,
        }
        impl ::core::fmt::Debug for EventType {
          fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            match self {
              EventType::PluginMessage => {
                f.debug_tuple("EventType::PluginMessage").finish()
              }
              EventType::InterconnectMessage => {
                f.debug_tuple("EventType::InterconnectMessage").finish()
              }
              EventType::DeviceAction => {
                f.debug_tuple("EventType::DeviceAction").finish()
              }
              EventType::ProviderAction => {
                f.debug_tuple("EventType::ProviderAction").finish()
              }
              EventType::DeeplinkAction => {
                f.debug_tuple("EventType::DeeplinkAction").finish()
              }
              EventType::TransportPacket => {
                f.debug_tuple("EventType::TransportPacket").finish()
              }
            }
          }
        }

        impl EventType{
          #[doc(hidden)]
          pub unsafe fn _lift(val: u8) -> EventType{
            if !cfg!(debug_assertions) {
              return unsafe { ::core::mem::transmute(val) };
            }

            match val {
              0 => EventType::PluginMessage,
              1 => EventType::InterconnectMessage,
              2 => EventType::DeviceAction,
              3 => EventType::ProviderAction,
              4 => EventType::DeeplinkAction,
              5 => EventType::TransportPacket,

              _ => panic!("invalid enum discriminant"),
            }
          }
        }

        #[repr(u8)]
        #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
        pub enum UiEvent {
          Click,
          Change,
          MouseEnter,
          MouseLeave,
          Focus,
          Blur,
          Submit,
          Input,
        }
        impl ::core::fmt::Debug for UiEvent {
          fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            match self {
              UiEvent::Click => {
                f.debug_tuple("UiEvent::Click").finish()
              }
              UiEvent::Change => {
                f.debug_tuple("UiEvent::Change").finish()
              }
              UiEvent::MouseEnter => {
                f.debug_tuple("UiEvent::MouseEnter").finish()
              }
              UiEvent::MouseLeave => {
                f.debug_tuple("UiEvent::MouseLeave").finish()
              }
              UiEvent::Focus => {
                f.debug_tuple("UiEvent::Focus").finish()
              }
              UiEvent::Blur => {
                f.debug_tuple("UiEvent::Blur").finish()
              }
              UiEvent::Submit => {
                f.debug_tuple("UiEvent::Submit").finish()
              }
              UiEvent::Input => {
                f.debug_tuple("UiEvent::Input").finish()
              }
            }
          }
        }

        impl UiEvent{
          #[doc(hidden)]
          pub unsafe fn _lift(val: u8) -> UiEvent{
            if !cfg!(debug_assertions) {
              return unsafe { ::core::mem::transmute(val) };
            }

            match val {
              0 => UiEvent::Click,
              1 => UiEvent::Change,
              2 => UiEvent::MouseEnter,
              3 => UiEvent::MouseLeave,
              4 => UiEvent::Focus,
              5 => UiEvent::Blur,
              6 => UiEvent::Submit,
              7 => UiEvent::Input,

              _ => panic!("invalid enum discriminant"),
            }
          }
        }

        #[doc(hidden)]
        #[allow(non_snake_case, unused_unsafe)]
        pub unsafe fn _export_handle_event_cabi<T: Guest>(arg0: i32,arg1: *mut u8,arg2: usize,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
        _rt::run_ctors_once();let result1 = {
          let len0 = arg2;
          let bytes0 = _rt::Vec::from_raw_parts(arg1.cast(), len0, len0);
          T::handle_event(EventType::_lift(arg0 as u8), _rt::string_lift(bytes0))
        };
        let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
        let vec3 = (result1.into_bytes()).into_boxed_slice();
        let ptr3 = vec3.as_ptr().cast::<u8>();
        let len3 = vec3.len();
        ::core::mem::forget(vec3);
        *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
        *ptr2.add(0).cast::<*mut u8>() = ptr3.cast_mut();
        ptr2
      } }
      #[doc(hidden)]
      #[allow(non_snake_case)]
      pub unsafe fn __post_return_handle_event<T: Guest>(arg0: *mut u8,) { unsafe {
        let l0 = *arg0.add(0).cast::<*mut u8>();
        let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
        _rt::cabi_dealloc(l0, l1, 1);
      } }
      #[doc(hidden)]
      #[allow(non_snake_case, unused_unsafe)]
      pub unsafe fn _export_handle_ui_event_cabi<T: Guest>(arg0: *mut u8,arg1: usize,arg2: i32,arg3: *mut u8,arg4: usize,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
      _rt::run_ctors_once();let result2 = {
        let len0 = arg1;
        let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
        let len1 = arg4;
        let bytes1 = _rt::Vec::from_raw_parts(arg3.cast(), len1, len1);
        T::handle_ui_event(_rt::string_lift(bytes0), UiEvent::_lift(arg2 as u8), _rt::string_lift(bytes1))
      };
      let ptr3 = (&raw mut _RET_AREA.0).cast::<u8>();
      let vec4 = (result2.into_bytes()).into_boxed_slice();
      let ptr4 = vec4.as_ptr().cast::<u8>();
      let len4 = vec4.len();
      ::core::mem::forget(vec4);
      *ptr3.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
      *ptr3.add(0).cast::<*mut u8>() = ptr4.cast_mut();
      ptr3
    } }
    #[doc(hidden)]
    #[allow(non_snake_case)]
    pub unsafe fn __post_return_handle_ui_event<T: Guest>(arg0: *mut u8,) { unsafe {
      let l0 = *arg0.add(0).cast::<*mut u8>();
      let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
      _rt::cabi_dealloc(l0, l1, 1);
    } }
    #[doc(hidden)]
    #[allow(non_snake_case, unused_unsafe)]
    pub unsafe fn _export_handle_ui_render_cabi<T: Guest>(arg0: *mut u8,arg1: usize,) { unsafe {#[cfg(target_arch="wasm32")]
    _rt::run_ctors_once();{
      let len0 = arg1;
      let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
      T::handle_ui_render(_rt::string_lift(bytes0))
    };
  } }
  #[doc(hidden)]
  #[allow(non_snake_case, unused_unsafe)]
  pub unsafe fn _export_handle_card_render_cabi<T: Guest>(arg0: *mut u8,arg1: usize,) { unsafe {#[cfg(target_arch="wasm32")]
  _rt::run_ctors_once();{
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    T::handle_card_render(_rt::string_lift(bytes0))
  };
} }
#[doc(hidden)]
#[allow(non_snake_case, unused_unsafe)]
pub unsafe fn _export_handle_load_cabi<T: Guest>() { unsafe {#[cfg(target_arch="wasm32")]
_rt::run_ctors_once();{
  T::handle_load()
};
} }
pub trait Guest {
  #[allow(async_fn_in_trait)]
  fn handle_event(a: EventType,b: _rt::String,) -> _rt::String;
  #[allow(async_fn_in_trait)]
  fn handle_ui_event(a: _rt::String,b: UiEvent,c: _rt::String,) -> _rt::String;
  #[allow(async_fn_in_trait)]
  fn handle_ui_render(a: _rt::String,) -> ();
  #[allow(async_fn_in_trait)]
  fn handle_card_render(a: _rt::String,) -> ();
  #[allow(async_fn_in_trait)]
  fn handle_load() -> ();
}
#[doc(hidden)]

macro_rules! __export_astrobox_psys_psys_plugin_0_1_0_cabi{
  ($ty:ident with_types_in $($path_to_types:tt)*) => (const _: () = {

    #[unsafe(export_name = "astrobox:psys/psys-plugin@0.1.0#handle-event")]
    unsafe extern "C" fn export_handle_event(arg0: i32,arg1: *mut u8,arg2: usize,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_handle_event_cabi::<$ty>(arg0, arg1, arg2) }
    }
    #[unsafe(export_name = "cabi_post_astrobox:psys/psys-plugin@0.1.0#handle-event")]
    unsafe extern "C" fn _post_return_handle_event(arg0: *mut u8,) {
      unsafe { $($path_to_types)*::__post_return_handle_event::<$ty>(arg0) }
    }
    #[unsafe(export_name = "astrobox:psys/psys-plugin@0.1.0#handle-ui-event")]
    unsafe extern "C" fn export_handle_ui_event(arg0: *mut u8,arg1: usize,arg2: i32,arg3: *mut u8,arg4: usize,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_handle_ui_event_cabi::<$ty>(arg0, arg1, arg2, arg3, arg4) }
    }
    #[unsafe(export_name = "cabi_post_astrobox:psys/psys-plugin@0.1.0#handle-ui-event")]
    unsafe extern "C" fn _post_return_handle_ui_event(arg0: *mut u8,) {
      unsafe { $($path_to_types)*::__post_return_handle_ui_event::<$ty>(arg0) }
    }
    #[unsafe(export_name = "astrobox:psys/psys-plugin@0.1.0#handle-ui-render")]
    unsafe extern "C" fn export_handle_ui_render(arg0: *mut u8,arg1: usize,) {
      unsafe { $($path_to_types)*::_export_handle_ui_render_cabi::<$ty>(arg0, arg1) }
    }
    #[unsafe(export_name = "astrobox:psys/psys-plugin@0.1.0#handle-card-render")]
    unsafe extern "C" fn export_handle_card_render(arg0: *mut u8,arg1: usize,) {
      unsafe { $($path_to_types)*::_export_handle_card_render_cabi::<$ty>(arg0, arg1) }
    }
    #[unsafe(export_name = "astrobox:psys/psys-plugin@0.1.0#handle-load")]
    unsafe extern "C" fn export_handle_load() {
      unsafe { $($path_to_types)*::_export_handle_load_cabi::<$ty>() }
    }
  };);
}
#[doc(hidden)]
pub(crate) use __export_astrobox_psys_psys_plugin_0_1_0_cabi;

#[cfg_attr(target_pointer_width="64", repr(align(8)))]
#[cfg_attr(target_pointer_width="32", repr(align(4)))]
struct _RetArea([::core::mem::MaybeUninit::<u8>; 2*::core::mem::size_of::<*const u8>()]);
static mut _RET_AREA: _RetArea = _RetArea([::core::mem::MaybeUninit::uninit(); 2*::core::mem::size_of::<*const u8>()]);

}

}
}
}
mod _rt {
  #![allow(dead_code, unused_imports, clippy::all)]
  pub use alloc_crate::string::String;
  pub use alloc_crate::vec::Vec;
  pub use alloc_crate::alloc;
  pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
    if cfg!(debug_assertions) {
      String::from_utf8(bytes).unwrap()
    } else {
      unsafe { String::from_utf8_unchecked(bytes) }
    }
  }
  pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
    if size == 0 {
      return;
    }
    unsafe {
      let layout = alloc::Layout::from_size_align_unchecked(size, align);
      alloc::dealloc(ptr, layout);
    }
  }
  pub unsafe fn invalid_enum_discriminant<T>() -> T {
    if cfg!(debug_assertions) {
      panic!("invalid enum discriminant")
    } else {
      unsafe { core::hint::unreachable_unchecked() }
    }
  }
  
  pub fn as_i32<T: AsI32>(t: T) -> i32 {
    t.as_i32()
  }

  pub trait AsI32 {
    fn as_i32(self) -> i32;
  }

  impl<'a, T: Copy + AsI32> AsI32 for &'a T {
    fn as_i32(self) -> i32 {
      (*self).as_i32()
    }
  }
  
  impl AsI32 for i32 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for u32 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for i16 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for u16 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for i8 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for u8 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for char {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for usize {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  #[cfg(target_arch = "wasm32")]
  pub fn run_ctors_once() {
    wit_bindgen::rt::run_ctors_once();
  }
  extern crate alloc as alloc_crate;
}

/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]

macro_rules! __export_psys_world_impl {
  ($ty:ident) => (self::export!($ty with_types_in self););
  ($ty:ident with_types_in $($path_to_types_root:tt)*) => (
  $($path_to_types_root)*::exports::astrobox::psys::psys_plugin::__export_astrobox_psys_psys_plugin_0_1_0_cabi!($ty with_types_in $($path_to_types_root)*::exports::astrobox::psys::psys_plugin);
  )
}
#[doc(inline)]
pub(crate) use __export_psys_world_impl as export;

#[cfg(target_arch = "wasm32")]
#[unsafe(link_section = "component-type:wit-bindgen:0.51.0:astrobox:psys@0.1.0:psys-world:encoded world")]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 1167] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\x8e\x08\x01A\x02\x01\
A\x04\x01B$\x01m\x06\x03div\x01p\x06button\x05input\x06select\x03opt\x04\0\x0cel\
ement-type\x03\0\0\x01m\x08\x05click\x06change\x0bmouse-enter\x0bmouse-leave\x05\
focus\x04blur\x06submit\x05input\x04\0\x08ui-event\x03\0\x02\x01m\x02\x03row\x06\
column\x04\0\x0eflex-direction\x03\0\x04\x01ks\x01ps\x01o\x02\x03s\x01p\x08\x01o\
\x02ss\x01p\x0a\x01r\x05\x0celement-type\x01\x04text\x06\x08children\x07\x09on-e\
vents\x09\x06styles\x0b\x04\0\x07element\x03\0\x0c\x01r\x02\x04addrs\x04names\x04\
\0\x0bdevice-info\x03\0\x0e\x01r\x03\x0cpackage-names\x0cversion-codey\x0cversio\
n-names\x04\0\x08app-info\x03\0\x10\x01@\x02\x01as\x01b\x0d\x01\0\x04\0\x06rende\
r\x01\x12\x01p\x0f\x01@\0\0\x13\x04\0\x19get-connected-device-list\x01\x14\x01j\0\
\x01s\x01@\x03\x01as\x01bs\x01cs\0\x15\x04\0\x11send-qaic-message\x01\x16\x01@\x02\
\x01as\x01bs\0\x15\x04\0\x1aregister-interconnect-recv\x01\x17\x01p\x11\x01j\x01\
\x18\x01s\x01@\x01\x01as\0\x19\x04\0\x17get-thirdparty-app-list\x01\x1a\x01@\x03\
\x01as\x01b\x11\x01cs\0\x15\x04\0\x09launch-qa\x01\x1b\x01@\0\0z\x04\0\x17timezo\
ne-offset-minutes\x01\x1c\x03\0\x1dastrobox:psys/psys-host@0.1.0\x05\0\x01B\x0d\x01\
m\x06\x0eplugin-message\x14interconnect-message\x0ddevice-action\x0fprovider-act\
ion\x0fdeeplink-action\x10transport-packet\x04\0\x0aevent-type\x03\0\0\x01m\x08\x05\
click\x06change\x0bmouse-enter\x0bmouse-leave\x05focus\x04blur\x06submit\x05inpu\
t\x04\0\x08ui-event\x03\0\x02\x01@\x02\x01a\x01\x01bs\0s\x04\0\x0chandle-event\x01\
\x04\x01@\x03\x01as\x01b\x03\x01cs\0s\x04\0\x0fhandle-ui-event\x01\x05\x01@\x01\x01\
as\x01\0\x04\0\x10handle-ui-render\x01\x06\x04\0\x12handle-card-render\x01\x06\x01\
@\0\x01\0\x04\0\x0bhandle-load\x01\x07\x04\0\x1fastrobox:psys/psys-plugin@0.1.0\x05\
\x01\x04\0\x1eastrobox:psys/psys-world@0.1.0\x04\0\x0b\x10\x01\0\x0apsys-world\x03\
\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.244.0\x10wit-\
bindgen-rust\x060.51.0";

#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
  wit_bindgen::rt::maybe_link_cabi_realloc();
}

